import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
    docs: [
        {
            type: 'autogenerated',
            dirName: '.'
        },
        // {
        //     type: 'link',
        //     label: 'GitHub',
        //     href: 'https://github.com/strut-rs/strut',
        // },
    ],
};

export default sidebars;
